backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: public/images
public_folder: /images

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "Instagram account"
            name: "instagram_account"
            widget: "string"
          - label: "Youtube account"
            name: "youtube_account"
            widget: "string"
          - label: "Facebook account"
            name: "facebook_account"
            widget: "string"
          - label: "Author"
            name: "author"
            widget: "string"
          - label: "Email Address"
            name: "email"
            widget: "string"
          - label: "Phone"
            name: "phone"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "posts"
    label: "Posts"
    editor:
      preview: false
    folder: "content/posts/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "A slug can have no spaces or special characters"]
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          required: true
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Seo title"
        name: "seo_title"
        widget: "string"
      - label: "Seo description"
        name: "seo_description"
        widget: "string"

      - label: "Fotoğraf"
        name: "image"
        widget: object
        fields:
          - name: src
            label: Image
            widget: image
          - name: alt
            label: Alt Tag
            widget: string
        choose_url: true
        media_library:
          config:
            multiple: false
      - label: "Body"
        name: "body"
        widget: "markdown"
